services:
  - type: web
    name: zerobasics-api
    env: python
    plan: free
    region: oregon
    buildCommand: cd backend && pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: cd backend && python3 migrate.py && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: zeroprjv2-db
          property: connectionString

